config/routes.rb
Rails.application.routes.draw do
  namespace :profile do
    get 'my/index'
    get 'my/edit'
    get 'my/update'
  end
  namespace :admin do
    get '/', to: 'home#index', as: 'index'

    resources :countries, :users, constraints: { id: /[0-9]+/ },
              except: [:show]

    resources :carriers, constraints: { id: /[0-9]+/ },
              only: [:index, :create, :destroy]
    get 'countries/update-all', to: 'countries#update_all', as: 'update_all'
  end

  scope '/profile' do
    get '/', to: 'profile#show', as: 'profile_my'
    get '/:id', to: 'profile#show', as: 'profile_show'
  end

  root to: 'home#index'

  devise_for :users, path: '',
             path_names: { sign_out: :logout, sign_in: :login },
             controllers: {
                 registrations: 'users/registrations',
             }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/country.rb
# == Schema Information
#
# Table name: countries
#
#  id               :bigint           not null, primary key
#  name             :string(255)
#  alpha_three_code :string(255)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Country < ApplicationRecord
  validates :name, presence: true
  validates :alpha_three_code, presence: true, length: { is: 3 }

  scope :codes, -> { pluck(:alpha_three_code) }

  def self.load_from_api(fetched_countries)
    codes = Country.codes

    fetched_countries.each do |country|
      unless codes.include? country[:alpha3Code]
        Country.create(
          name: country[:name],
          alpha_three_code: country[:alpha3Code]
        )
      end
    end
  end
end

app/controllers/admin/countries_controller.rb
class Admin::CountriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @countries = policy_scope(
        Country,
        policy_scope_class: Admin::CountryPolicy::Scope
    ).page(params[:page]).per(10)
  end

  def new
    @country = Country.new
    authorize [:admin, country]
  end

  def create
    @country = Country.new(country_params)
    authorize [:admin, country]

    if @country.save
      redirect_to admin_countries_path
    else
      render :new
    end
  end

  def edit
    authorize [:admin, country]
  end

  def update
    authorize [:admin, country]

    if country.update(country_params)
      redirect_to admin_countries_path
    else
      render :edit
    end
  end

  def destroy
    authorize [:admin, country]

    country.delete
    redirect_to admin_countries_path
  end

  def update_all
    Country.load_from_api Countries::ListFetcher.fetch

    flash[:notice] = 'Countries have updated successfully'
    redirect_to admin_countries_path
  end

  private

  def country_params
    params.require(:country).permit(:name, :alpha_three_code)
  end

  def country
    @country ||= Country.find(params[:id])
  end

  helper_method :country
end

app/helpers/admin/countries_helper.rb
module Admin::CountriesHelper
end

app/views/admin/countries/_add_form.html.slim
= form_with model: [:admin, country], local: true, class: 'admin__form admin-form' do |country_form|
  = render 'form_body', country_form: country_form, country: country
  .row
    .col-sm-12
      .d-flex.justify-content-end
        = country_form.submit 'Add', class: 'admin-form__submit'

app/views/admin/countries/_country.html.slim
tr.admin-list__item
  td = country.id
  td = country.name
  td = country.alpha_three_code
  td
    = link_to 'Edit', edit_admin_country_path(country), class: 'admin-list__btn admin-list__btn--edit'
    = link_to 'Destroy', admin_country_path(country), method: :delete, class: 'admin-list__btn admin-list__btn--del',
            data: {confirm: "Are you sure?"}

app/views/admin/countries/_edit_form.html.slim
= form_with model: [:admin, country], local: true, class: 'admin__form admin-form' do |country_form|
  = render 'form_body', country_form: country_form, country: country
  .row
    .col-sm-12
      .d-flex.justify-content-end
        = country_form.submit 'Edit', class: 'admin-form__submit'

app/views/admin/countries/_form_body.html.slim
.row
  .col-sm-12.col-md-6
    .admin-form__group.admin-form__group
      = country_form.label :name, class: 'admin-form__label'
      = country_form.text_field :name,
              class: "admin-form__input #{ 'admin-form__input--error' unless country.errors[:name].empty? }"
      - if country.errors[:name]
        p.admin-form__error= country.errors.full_messages_for(:name).first
  .col-sm-12.col-md-6
    .admin-form__group.admin-form__group
      = country_form.label :alpha_three_code, class: 'admin-form__label'
      = country_form.text_field :alpha_three_code,
              class: "admin-form__input #{ 'admin-form__input--error' unless country.errors[:alpha_three_code].empty? }"
      - if country.errors[:alpha_three_code]
        p.admin-form__error= country.errors.full_messages_for(:alpha_three_code).first

app/views/admin/countries/edit.html.slim
.container
  .row
    .col-sm-12
      .admin-list-panel
        h1.admin-list-panel__title
          | edit country #
          = country.id
        = link_to 'Back to list', admin_countries_path, class: 'admin-list-panel__btn'

  .row
    .col-sm-12
      .admin-form__container
        = render 'edit_form'

app/views/admin/countries/index.html.slim
section.users
  .container
    .row
      .col-sm-12
        .admin-list-panel
          h1.admin-list-panel__title Countries
          = link_to 'Add', new_admin_country_path, class: 'admin-list-panel__btn'

    .row
      .col-md-12
        .admin-list.countries
          - unless @countries.empty?
            table#admin-countries-table.table
              thead
                tr
                  th ID
                  th Name
                  th Alpha Three Code
                  th Actions
              tbody
                = render @countries
            .admin-list__pagination.admin-pagination
              = paginate @countries, views_prefix: 'admin'
          - else
            h2.countries__empty No items

app/views/admin/countries/new.html.slim
.container
  .row
    .col-sm-12
      .admin-list-panel
        h1.admin-list-panel__title new country
        = link_to 'Back to list', admin_countries_path, class: 'admin-list-panel__btn'

  .row
    .col-sm-12
      .admin-form__container
        = render 'add_form'