config/routes.rb
Rails.application.routes.draw do
  namespace :profile do
    get 'my/index'
    get 'my/edit'
    get 'my/update'
  end
  namespace :admin do
    get '/', to: 'home#index', as: 'index'

    resources :countries, :users, constraints: { id: /[0-9]+/ },
              except: [:show]

    resources :carriers, constraints: { id: /[0-9]+/ },
              only: [:index, :create, :destroy]
    get 'countries/update-all', to: 'countries#update_all', as: 'update_all'
  end

  scope '/profile' do
    get '/', to: 'profile#show', as: 'profile_my'
    get '/:id', to: 'profile#show', as: 'profile_show'
  end

  root to: 'home#index'

  devise_for :users, path: '',
             path_names: { sign_out: :logout, sign_in: :login },
             controllers: {
                 registrations: 'users/registrations',
             }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/partials/header/_guest.html.slim
header.header.header--guest
  .container
    .row
      .col-md-3
        = link_to root_path, class: 'header__logo logo'
          h3.logo__title reviewer
          p.logo__subtitle The top review platform
      .col-md-9.d-flex.justify-content-end
        - if current_page?(new_user_registration_path) || controller.controller_name == 'registrations'
          = link_to 'Login', root_path, class: 'header__auth-btn'
        - elsif current_page?(user_session_path) || controller.controller_name == 'sessions'
          = link_to 'Register', new_user_registration_path, class: 'header__auth-btn'

app/views/partials/header/_user.html.slim
header.header
  .container
    .row
      .col-md-12.d-flex.justify-content-between
        .d-flex
          = link_to root_path, class: 'header__logo logo' do
            h3.logo__title reviewer
            p.logo__subtitle The top review platform
          nav.header__nav.nav
            ul.nav__list
              li.nav__item
                = active_link_with_block root_path, class: 'nav__link', active: 'nav__link--active' do
                  = fa_icon 'home'
                  span.nav__link-text Home
              li.nav__item
                = active_link_with_block admin_index_path, class: 'nav__link', active: 'nav__link--active' do
                  = fa_icon 'user-o'
                  span.nav__link-text Admin
        .d-flex.justify-content-end
          .header__notify.notify.notify--active
            = fa_icon 'bell-o', class: 'notify__icon'
          .header__user-card.user-card
            = image_tag 'avatar.jpg', class: 'user-card__image'
            .user-card__text
              p.user-card__name
                = current_user.full_name
              p.user-card__type
                | Pro
            = fa_icon 'chevron-down', class: 'user-card__down'

            .user-card__profile-dropdown.profile-dropdown.profile-dropdown--hidden
              ul.profile-dropdown__list
                li.profile-dropdown__item
                  = link_to 'Profile', profile_my_path, class: 'profile-dropdown__link'
                  = link_to 'Logout', destroy_user_session_path, class: 'profile-dropdown__link', method: :delete