config/routes.rb
Rails.application.routes.draw do
  namespace :profile do
    get 'my/index'
    get 'my/edit'
    get 'my/update'
  end
  namespace :admin do
    get '/', to: 'home#index', as: 'index'

    resources :countries, :users, constraints: { id: /[0-9]+/ },
              except: [:show]

    resources :carriers, constraints: { id: /[0-9]+/ },
              only: [:index, :create, :destroy]
    get 'countries/update-all', to: 'countries#update_all', as: 'update_all'
  end

  scope '/profile' do
    get '/', to: 'profile#show', as: 'profile_my'
    get '/:id', to: 'profile#show', as: 'profile_show'
  end

  root to: 'home#index'

  devise_for :users, path: '',
             path_names: { sign_out: :logout, sign_in: :login },
             controllers: {
                 registrations: 'users/registrations',
             }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/carrier.rb
# == Schema Information
#
# Table name: carriers
#
#  id         :bigint           not null, primary key
#  name       :string(255)
#  slug       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Carrier < ApplicationRecord
  validates :name, presence: true

  before_save :generate_slug!

  def generate_slug!
    self.slug = self.name.parameterize(separator: '_')
  end
end

app/controllers/admin/carriers_controller.rb
class Admin::CarriersController < ApplicationController
  before_action :authenticate_user!

  def index
    @carrier = Carrier.new
  end

  def create
    @carrier = Carrier.new(carrier_params)
    authorize [:admin, carrier]

    if @carrier.save
      redirect_to admin_carriers_path
    else
      render :index
    end
  end

  def destroy
    authorize [:admin, carrier]

    carrier.delete
    redirect_to admin_carriers_path
  end

  private

  def carrier_params
    params.require(:carrier).permit(:name)
  end

  def carrier
    @carrier ||= Carrier.find(params[:id])
  end

  def carriers
    @carriers ||= policy_scope(
        Carrier,
        policy_scope_class: Admin::CarrierPolicy::Scope
    ).page(params[:page]).per(10)
  end

  helper_method :carrier
  helper_method :carriers
end

app/helpers/admin/carriers_helper.rb
module Admin::CarriersHelper
end

app/views/admin/carriers/_carrier.html.slim
tr.admin-list__item
  td = carrier.id
  td = carrier.name
  td = carrier.slug
  td
    = link_to 'Destroy', admin_carrier_path(carrier), method: :delete, class: 'admin-list__btn admin-list__btn--del',
            data: {confirm: "Are you sure?"}

app/views/admin/carriers/_form_body.html.slim
.row
  .col-sm-12
    .admin-form__group.admin-form__group
      = carrier_form.label :name, class: 'admin-form__label'
      = carrier_form.text_field :name,
              class: "admin-form__input #{ 'admin-form__input--error' unless carrier.errors[:name].empty? }"
      - if carrier.errors[:name]
        p.admin-form__error= carrier.errors.full_messages_for(:name).first

app/views/admin/carriers/index.html.slim
section.users
  .container
    .row
      .col-sm-12
        .admin-list-panel
          h1.admin-list-panel__title Carriers

    .row
      .col-md-8
        .admin-list.carriers
          - unless carriers.empty?
            table#admin-carriers-table.table
              thead
                tr
                  th ID
                  th Name
                  th Slug
                  th Actions
              tbody
                = render carriers
            .admin-list__pagination.admin-pagination
              = paginate carriers, views_prefix: 'admin'
          - else
            h2.admin-list__empty No items

      .col-md-4
        .admin-form__container
          = form_with model: [:admin, carrier], local: true, class: 'admin__form admin-form' do |carrier_form|
            = render 'form_body', carrier_form: carrier_form, carrier: carrier
            .row
              .col-sm-12
                .d-flex.justify-content-end
                  = carrier_form.submit 'Add', class: 'admin-form__submit'